export const SEARCHFIELD_ITEM = "SEARCHFIELD_ITEM";
export const SAVED_GIFS = "SAVED_GIFS";
export const REQUEST_GIFS_PENDING = "REQUEST_GIFS_PENDING";
export const REQUEST_GIFS_SUCCESS = "REQUEST_GIFS_SUCCESS";
export const REQUEST_GIFS_FAILED = "REQUEST_GIFS_FAILED";
